spring:
  data:
    mongodb:
      uri: mongodb+srv://ricardo:LqpLBxHkDyikucBi@cluster-ieti.htfx4.mongodb.net/fileDatabase?retryWrites=true&w=majority
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB